---
all:
  children:
    app_servers:
      hosts:
        app_server:
          ansible_host: 18.232.124.19
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /Users/lucifer/.ssh/JathinDev.pem
          app_port: 3000
          node_version: "20.x"
    
    db_servers:
      hosts:
        db_server:
          ansible_host: 44.222.197.115
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /Users/lucifer/.ssh/JathinDev.pem
          mongodb_version: "7.0"
          mongodb_port: 27017
    
    monitoring_servers:
      hosts:
        nagios_server:
          ansible_host: 3.236.221.146
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /Users/lucifer/.ssh/JathinDev.pem
          nagios_admin_user: nagiosadmin
          nagios_admin_password: "changeme123"
