---
all:
  children:
    app_servers:
      hosts:
        app_server:
          ansible_host: 3.238.73.59
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /Users/lucifer/.ssh/JathinDev.pem
          app_port: 3000
          node_version: "20.x"
    
    db_servers:
      hosts:
        db_server:
          ansible_host: 98.92.251.77
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /Users/lucifer/.ssh/JathinDev.pem
          private_ip:
          mongodb_version: "7.0"
          mongodb_port: 27017
    
    monitoring_servers:
      hosts:
        nagios_server:
          ansible_host: 100.28.225.138
          ansible_user: ubuntu
          ansible_ssh_private_key_file: /Users/lucifer/.ssh/JathinDev.pem
          nagios_admin_user: nagiosadmin
          nagios_admin_password: "changeme123"
